RustAudio/cpal

- alsa-sys/src/lib.rs
I was really happy to find your work on cpal, as I'm interested in using rust for audio programming.
I changed the suffixes on ints in alsa from 'u' to 'us' as per compiler output in Rust alpha. 
Jason
> Changed integer suffix from 'u' to 'us'

- alsa-sys/src/lib.rs
The `us` suffixes have long been replaced with `usize`, but in this case, no suffixes are required at all.
I did not test this because I am at a Windows box at the moment. It should work in theory, and I hope this triggers the Travis build, so we will know.
**Edit**: The Travis build passed.
> Remove integer suffixes in alsa-sys

- src/wasapi/mod.rs
When samples format is not supported, cpal panics with "not yet implemented" message, which is not useful in bug reports.
This adds samples format to the message.
Signed-off-by: Mariusz Ceier <mceier+cpal@gmail.com>
> Add more detailed message to panic

- Cargo.toml
- examples/beep.rs
- src/alsa/enumerate.rs
- src/alsa/mod.rs
- src/lib.rs
- src/samples_formats.rs
- src/wasapi/com.rs
- src/wasapi/enumerate.rs
- src/wasapi/mod.rs
- src/wasapi/voice.rs
So this is a preliminary PR that changes the API to correctly enumerate end points.
On Windows it blocks on https://github.com/retep998/winapi-rs/pull/195, and on Linux/OSX it's not implemented.
Changes:
- Adds `Endpoint`, `get_endpoints_list`, `get_default_endpoint`, `EndpointsIterator`, `get_supported_formats_list`, `Format`, `SupportedFormatsIterator`.
- `Voice::new` takes a `&Endpoint` and a `&Format` and returns a `Result`.
> Global cleanup

- src/alsa/mod.rs
- src/coreaudio/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/voice.rs
And removes the getters from the various implementations.
> Store the format in the public `Voice` struct

- src/alsa/mod.rs
On a device with no sound (such as [Travis-CI][travis]) I could get a default endpoint but enumerating the formats would then panic. This patch adds the error code that my case returned, and which I believe should be caught instead of panic.
Looking at the code, I think a more rigorous change would be nice, but in the meantime I propose merging this fix.
[travis]: https://travis-ci.org/mvdnes/rboy/builds/85080893
> Catch another 'device not found' error code with ALSA

- Cargo.toml
mipsel is mostly used on embedded multimedia devices like settop bockes for eg.
This change will allow building cpal for those platforms aswell
> allow for building for mipsel targets

- src/alsa/mod.rs
The old method always returned _RUNNING on some machines.
This new method seems to produce the expected behaviour.
Note: -32 is probably -EPIPE, but the appropriate constant was not
available at this time.
> Fix underflow detection for alsa

- alsa-sys/Cargo.toml
- alsa-sys/src/lib.rs
The pollfd struct got added to libc in v0.2.7, so now we can uncomment those commented functions, enabling us to use async I/O for ALSA.
> alsa-sys: Add pollfd

- src/coreaudio/mod.rs
cpal fails to compile on OSX without the get_period method on Voice, this PR provides it as it appears in the wasapi backend. The examples work as intended.
> [osx] Add get_period to Voice

- Cargo.toml
- src/coreaudio/mod.rs
This is a follow up to (and is based upon) the changes introduced in #121.
The beep example runs fine for me and `cargo test` passes on my machine.
Tested on OS X 10.10.5.
Closes #104.
> Update coreaudio backend to new futures-rs oriented design introduced in #121. Take 2.

- Cargo.toml
- README.md
- examples/beep.rs
- examples/enumerate.rs
- src/alsa/mod.rs
- src/coreaudio/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/mod.rs
- src/wasapi/voice.rs
Windows-only for now.
Changes:
- `Voice::new()` requires passing an `EventLoop` which can be created with `EventLoop::new()`.
- `Voice::new()` now returns a `(Voice, SamplesStream)`. The `SamplesStream` implements the `futures::stream::Stream` trait and produces `UnknownTypeBuffer` objects.
- The `UnknownTypeBuffer` and `Buffer` structs are now `'static`.
- `EventLoop::run()` needs to be called on a thread in order to be guarateed to have the stream produce buffers.
- All the old methods that are now irrelevant have been removed.
On Windows, the implementation now calls `SetEventHandle` on the audio client. Calling `SamplesStream::poll()` checks whether the `Event` is signalled and returns a buffer if so. Calling `SamplesStream::schedule()` adds the event to a list in the event loop. …
> Draft for switching to futures

- examples/beep.rs
- src/alsa/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/voice.rs
here is a try to update cpal to use futures 0.1.1 instead of yanked futures 0.1.0, it is related to issue 129
change is made on streams: when poll return not ready, the function schedule the task on the event loop.
also there is change for users: in beep example the user spawn a task for the stream and use its own executor to handle its execution.
current state of this branch:
* alsa is OK for me: beep example works.
* wasapi compile but the execution on wine of beep.exe sounds crap
* coreaudio nothing has been made
> update to futures 0.1.1: alsa wasapi

- src/coreaudio/mod.rs
After applying this, #131 works for me (beep example works fine) :+1:
> Do not lock inner twice. Fixes bug in osx futures 0.1.1 update.

- examples/beep.rs
- src/alsa/mod.rs
snd_pcm_pause could have been used but not all hardware implement it, so
I propose not to use it.
In this implementation:
there are two kind of scheduling: wait for resume signal and wait for
pcm to be available
if the stream is paused then it return notready and wait for resume
the event loop is different as it manages descriptors corresponding to
voices according to the nature of the scheduling.
there is still a FIXME: in voice.play the is signal is send even if
the event loop wasn't waiting for resume.
It doesn't seem to create any issue. But it happens when you write
voice.pause();voice.play();
> impl play and pause for ALSA

- Cargo.toml
Fixes build for 32-bit mac. Tested locally in both configs, works just fine!
Also, can I request a minor release be published after merge? Would be nice to use this ASAP :) Thanks!
> Add coreaudio-rs dependency for i686-apple-darwin

- src/alsa/mod.rs
snd_pcm_sw_params_set_avail_min was being hardcoded to 4096, which
seems to be problematic for lower sample rates.  This update sets
the value to the buffer size as supplied by snd_pcm_get_params(),
which is what alsa own sample code does.
This should fix https://github.com/tomaka/cpal/issues/142
> alsa: set sw_params_set_avail_min based on get_params buffer size

- Cargo.toml
- src/alsa/mod.rs
#145 Fixed the stalling (#142), but there still was a stuttering problem.
Passing `period` instead of `buffer` to `snd_pcm_sw_params_set_avail_min` fixes the stuttering.
Also crate version is bumped to ~`0.4.3`~ `0.4.4`in this PR.
> alsa: Pass period instead of buffer to snd_pcm_sw_params_set_avail_min

- alsa-sys/Cargo.toml
The build script requires pkg-config, which isn't available when cross compiling.
Mark alsa-sys as linking to alsa allows cargo configuration to bypass the build script.
cf http://doc.crates.io/build-script.html#the-links-manifest-key
> Mark alsa-sys as linking to alsa

- src/coreaudio/mod.rs
Fix in relation to #148 with the loop in EventLoop::run optimised out in a release build on macOS, doesn't feel very elegant, so am open to suggestions for something nicer.
> Fix for loop in EventLoop::run optimised out in a release build on macOS

- src/alsa/mod.rs
- src/lib.rs
Replace linux-only eventfd() with pipe() to enable use on *BSDs for alsa.
Add FreeBSD to supported OSes. 
Print warning to stdout if using null device.
Note: not tested on Linux.
> Fixes for *BSDs

- examples/beep.rs
> examples: Avoid f32 precision loss in beep example

- CHANGELOG.md
- examples/beep.rs
- src/alsa/mod.rs
- src/coreaudio/enumerate.rs
- src/coreaudio/mod.rs
- src/emscripten/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/endpoint.rs
The ALSA API reports that devices support a wide range of samples rate, as it does the conversion to the final rate itself. Right now cpal handles that by returning one `Format` for each possible samples rate, which results in thousands of elements.
This PR fixes this design issue by producing a list of `SupportedFormat` elements, instead of `Format`. The difference between `SupportedFormat` and `Format` is that the former contains a range of samples rate. Building a voice still expects a `Format`, and the user must perform the conversion.
> Add SupportedFormat

- CHANGELOG.md
- src/alsa/mod.rs
This commit also ensures that the Voice is initially paused when returned to remain consistent with the curent state of the rest of the CPAL backends (at least I think they're paused by default at the moment?). Related discussion on this at #175.
The ALSA docs mention that not all hardware supports pause functionality, so we check for this using the `snd_pcm_hw_params_can_pause` function. Currently, `pause` and `play`  only do something if `can_pause` is `true`. I wonder what we should do In the case that  the hardware doesn't support pause functionality? Should we just submit silence and not call the callback? Or just do nothing at all as is currently the case?
> Implement `pause` and `play` for ALSA backend

- CHANGELOG.md
- src/coreaudio/enumerate.rs
- src/coreaudio/mod.rs
- src/lib.rs
- Set the audio unit properties directly to make CoreAudio create an interleaved 2-channel buffer which can be passed directly to the user callback.
- Use `slice::from_raw_parts_mut` to produce a direct mutable slice of the OS buffer for the cpal callback to write to.
- Clean up some compile warnings.
No consideration of the stream format requested, this only supports f32 for now.
Fixes #181
> [coreaudio] Remove intermediate buffer

- src/coreaudio/mod.rs
The last commit to coreaudio/mod.rs added a call to convert_error, but
that function was removed earlier. Remove the call to fix the build.
> Fix coreaudio build

- src/coreaudio/mod.rs
- src/lib.rs
This PR fixes broken osx build:
1. Fixes tomaka/rodio#145 (callback sync error)
2. Fixes missing `convert_error` caused by most recent PRs. #182 #183
> Fix macos build

- CHANGELOG.md
- Cargo.toml
There does not seem to be any major API breakage, however the emscripten
and macos backends have been pretty heavily refactored so I thought it
best to bump to 0.6 (rather than 0.5.2) just in case there is any subtle
behavioural breakage. Happy to change this to 0.5.2 though if someone
can confirm there will be no downstream breakage.
> Publish v0.6.0

- CHANGELOG.md
- src/coreaudio/mod.rs
This is an attempt at properly handling the given format for the `build_voice` method in the coreaudio backend. Currently the `Endpoint` is still ignored. I don't have a mac on me atm but I managed to test a patch similar to this on one earlier today that ran successfully. If there are any mac users that could test this that would be greatly appreciated!
I'll likely follow this up soon with #194.
This closes #180.
> Implement format handling in `build_voice` macos backend

- CHANGELOG.md
- Cargo.toml
- examples/enumerate.rs
- src/coreaudio/enumerate.rs
- src/coreaudio/mod.rs
Based on #195.
Also implements proper handling of the given `Endpoint` in the
macos implementation of the `build_voice` method.
Updates to the latest coreaudio-sys and coreaudio-rs which include the
additional necessary frameworks.
Also adds a line that prints the name of the default device in the
`enumeration.rs` example.
Updates the CHANGELOG for this PR.
Closes #194.
Related to #180.
Related external issues:
- RustAudio/coreaudio-sys#4
- RustAudio/coreaudio-rs#57
>  [coreaudio] Implement Endpoint and Format Enumeration

- CHANGELOG.md
- examples/beep.rs
- src/alsa/mod.rs
- src/coreaudio/mod.rs
- src/emscripten/mod.rs
- src/lib.rs
- src/wasapi/endpoint.rs
- src/wasapi/voice.rs
Related discussion at #187.
This removes the ChannelPosition API from the lib root and updates the
ALSA backend and examples accordingly. The other backends have not yet
been updated.
The windows backend now assumes the channel position order is equal to
the channel position mask order. E.g. channel 0 will always be front
left, channel 1 will always be front right, etc. It seems that this order was
previously enforced anyway and would return a FormatError otherwise, so
I can't imagine this should affect windows users too much. Please let me
know if I'm wrong or the windows fix could be improved!
cc @tomaka
> Remove unused `ChannelPosition` API (update all backends and examples accordingly)

- CHANGELOG.md
- examples/beep.rs
- src/alsa/mod.rs
- src/coreaudio/mod.rs
- src/emscripten/mod.rs
- src/lib.rs
- src/wasapi/endpoint.rs
- src/wasapi/voice.rs
Previously mentioned at #29.
This changes the `SamplesRate` and `ChannelsCount` type names to the more idiomatic names `SampleRate` and `ChannelCount`.
The `s` on the end of `Sample` and `Channel` is unnecessary as both `Rate` and `Count` already imply plurality. A quick google will show that the term "sample rate" is ubiquitous throughout existing audio libraries, whereas there are no previous uses of "samples rate" within APIs that I can find.
This also renames the `samples_rate` fields to `sample_rate`.
> Rename `SamplesRate` to `SampleRate` and `ChannelsCount` to `ChannelCount`

- Cargo.toml
- src/wasapi/com.rs
- src/wasapi/endpoint.rs
- src/wasapi/mod.rs
- src/wasapi/voice.rs
Adds only the necessary cargo features to reduce compile time and reduce
the chance of linking errors occurring for unused libraries (e.g.
d3d12.dll fails to link on my win10 VM).
I thought I'd try and land this before before working on the wasapi
backend implementation for #201.
Tested both beep.rs and enumerate.rs and they work fine with the update.
> Update winapi version from 0.2 to 0.3

- .gitignore
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/beep.rs
- examples/enumerate.rs
- examples/record_wav.rs
- src/alsa/enumerate.rs
- src/alsa/mod.rs
- src/coreaudio/enumerate.rs
- src/coreaudio/mod.rs
- src/emscripten/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/device.rs
- src/wasapi/mod.rs
- src/wasapi/stream.rs
This update prepares for adding input stream support by removing the
`Endpoint` type (which only supports output streams) in favour of a more
general `Device` type which may support any number of input or output
streams. Previously discussed at #117.
The name `Voice` has been replaced with the more ubiquitous name
stream. See #118 for discussion on this.
Also introduces a new `StreamData` type which is now passed to the
`EventLoop::run` callback rather than the `UnknownTypeBuffer`.
`StreamData` allows for passing either `Input` data to be read, or
`Output` data to be written. ~~As of this `PR`, the `Input` variant is just
a unit type and is not yet implemented.~~
All backends have been updated for the API changes, ~~however input
stream functionality remains unimplemented across each …
> Update to a more general Device and Stream API. Add support for input streams (E.g. microphone). Add default format methods.

- CHANGELOG.md
- Cargo.toml
- src/coreaudio/mod.rs
Currently when building an input stream the coreaudio backend only
specifies the sample rate for the audio unit, however coreaudio requires
that the audio unit sample rate matches the device sample rate.
This changes the `build_input_stream` behaviour to:
1. Check if the device sample rate differs from the desired one.
2. If so, check that there are no existing audio units using the device
at the current sample rate. If there are, panic with a message
explaining why.
3. Otherwise, change the device sample rate.
4. Continue building the input stream audio unit as normal.
Closes #213.
> [coreaudio] Fix handling of non-default sample rates for input streams

- CHANGELOG.md
In the process of porting a library from `cpal` 0.6 to 0.7, I noticed some breaking changes were not mentioned in the changelog.
> Add missing braking changes introduced into 0.7

- src/lib.rs
The other error types have these, but not this one.
> Implement Display and Error for DefaultFormatError

- CHANGELOG.md
- src/wasapi/stream.rs
The `playing` variable was miscarried in wasapi, resulting in it rejecting to resume a stream.
> Fix the PauseStream handler to flip the `playing` bit.

- src/wasapi/stream.rs
On Windows, creating a stream, destroying it and then trying to re-create one was not working. The issue was that the index used by the PlayStream command to find the stream & handle was the StreamId, which keeps incrementing. The second stream had stream id 1, but its index was 0. 
This fixes the issue by making sure we're not using the stream id as an offset, but always finding the right stream by its id. It may not be as performant as a direct access, but we should rarely have more than a few streams.
> WASPI - Fix stream start after destroy

- src/coreaudio/mod.rs
- src/lib.rs
- src/wasapi/device.rs
The internal alsa, null and emscripten Device implementations already implemented Debug; but the coreaudio and wasapi ones, and therefore also the wrapper, did not.
I decided to eschew the `Device(…)` wrapping in the outer layer (hence a custom implementation rather than `#[derive(Debug)]`), because `Device(Device)`, `Device(Device { … })` and so forth all look better without the extra `Device(…)` wrapping.
On the wasapi and coreaudio implementations I put both the pointer and name. Name because it’s useful, pointer because on Windows at least I believe duplicated names are possible. (e.g. two monitors that include monitors, of the same type; I haven’t strictly confirmed this, because I killed those off harshly on my machine and don’t want to reinstate them.)
I do not have access to a …
> impl Debug for Device

- src/lib.rs
Just a missing `and` and two minor text changes where the flow of things seemed to repeat or felt unclear.
Thanks so much for your work, looking forward to trying the library!
Update: Fixed another text issue discovered later
> Minor textual corrections in crate documentation intro

- src/alsa/mod.rs
The issue originated from an logic error. Let's avoid casting like a blind by the way.
Vec are now zero-filled from the start. There's no point in leaving heap uninitialized ([ref](https://github.com/rust-lang/rust/issues/54628)).
And hey, please do not wrap the entire function in unsafe. It's a disaster to audit.
gg.
> Fix #254, logic error in frame/sample size

- src/alsa/mod.rs
- src/lib.rs
Instead of taking the easy way out and killing the whole program by panicking, device enumeration and stream creation will now report the error variant 'Unknown' as suggested in #216 
Also added an "InvalidArgument" variant for the infamous -22 error (this should resolve #247 and make #206 more handable)
> Added error handling for unknown ALSA device errors

- src/alsa/mod.rs
- src/coreaudio/mod.rs
- src/emscripten/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/mod.rs
- src/wasapi/stream.rs
- ALSA backend: reuse the buffers
- Make `InputBuffer` and `OutputBuffer` types just a wrapper of slice
* Buffer is now submitted at the end of callback
> Better buffer handling

- src/wasapi/device.rs
- src/wasapi/stream.rs
CPAL was panicking when I was switching my headset off.
Also, it was impossible to detect default device changes by comparing the current default device with the previously obtained one.
The patch fixes these problems on Windows, I can now keep streaming an audio across the changes of the default device.
> Switching the headset on and off

- src/wasapi/stream.rs
I have encountered the panic described in #231 (but different test case). The cause is that `IAudioCaptureClient::GetBuffer` method may return `AUDCLNT_S_BUFFER_EMPTY`, which is success HRESULT, and make the buffer null.
ref: [IAudioCaptureClient::GetBuffer | Microsoft Docs](https://docs.microsoft.com/ja-jp/windows/desktop/api/audioclient/nf-audioclient-iaudiocaptureclient-getbuffer)
> Assertion failed in Windows

- examples/feedback.rs
I created this example to test:
1. the latency required on my system when feeding the defualt input directly back into the default output and
2. that stream IDs are actually unique between different streams and that they match the yielded StreamData.
Just thought I'd post in case you'd like to include it as another example.
> Add an example that demonstrates feeding input directly to output with some latency

- src/lib.rs
Since #269 this `panic!` is certainly unnecessary as `InputBuffer` and
`OutputBuffer` are a thin wrapper around a slice. That said, I'm
struggling to understand exactly why this `panic!` was necessary in the
first place.
This closes #228.
> Remove unnecessary panic! from OutputBuffer Deref impl

- Cargo.toml
- appveyor.yml
- examples/beep.rs
- examples/enumerate.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/alsa/enumerate.rs
- src/alsa/mod.rs
- src/coreaudio/enumerate.rs
- src/coreaudio/mod.rs
- src/emscripten/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/device.rs
- src/wasapi/mod.rs
- src/wasapi/stream.rs
The aim of this PR is to overhaul the way that errors are handled throughout the crate as discussed within #268.
I will continue to update the following list and commit to this PR as I make progress. Feel free to comment at any stage!
> Error Handling Overhaul

- examples/beep.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/alsa/mod.rs
- src/coreaudio/mod.rs
- src/emscripten/mod.rs
- src/lib.rs
- src/null/mod.rs
- src/wasapi/stream.rs
Add new `StreamEvent` type - enables more flexible user callback API.
This adds the following types:
- `StreamEvent`
- `CloseStreamCause`
- `StreamError`
These allow for notifying the user of the following events:
- A stream has been played.
- A stream has been paused.
- A stream has been closed due to the user destroying stream.
- A stream has been closed due to an error.
Closes #268.
> User Callback API `StreamEvent` Overhaul

- CHANGELOG.md
- Cargo.toml
- asio-sys/Cargo.toml
- src/lib.rs
- src/platform/mod.rs
- src/traits.rs
This is quite a significant update for CPAL, including a number of
breaking changes. Here is a list of the major changes along with
links to where you can find more information:
- A `Host` API has been introduced in #289 along with a follow-up
refactor in #295. Please see the examples for a demonstration of how
to update your code. The necessary changes should hopefully be
minimal. If this has caused you any major difficulty please let us
know in an issue!
- An ASIO host has been introduced in #292. This adds support for
Steinberg's ASIO audio driver API on Windows. Please see the ASIO
section of the README for more information on how to setup CPAL with
ASIO support for your project.
- The user callback API has been overhauled to emit `StreamEvent`s
rather than buffers in order to support …
> Update CPAL to version 0.10.0.

- src/host/alsa/mod.rs
The hardcoded errno was replaced by a constant, and `snd_pcm_prepare` was replaced by `snd_pcm_recover` per best practice (the underlying implementation seems same for now, though).
> Small tweak for ALSA underruns

- .circleci/config.yml
The Android build has been broken for a while; we don't have cfg-gated code for Android anyway for now.
> Disable Android CI target

- src/host/alsa/enumerate.rs
- src/host/alsa/mod.rs
- src/host/coreaudio/mod.rs
cc #316
The windows backend still uses `mem::uninitialized()` but only because there is no CI set up to test it (#318)
> Remove mem::uninitialized() from coreaudio and alsa backends

- src/host/alsa/mod.rs
For me, cpal fails with EINVAL when cpal tries to set hw_params. I've found that relaxing the buffer size constraint solves the problem for me.
> Remove the (arbitary) restriction on buffer size

- src/host/alsa/mod.rs
Tested on Linux, seems to working fine. The `snd_pcm_avail` function performs additional work for synchronization (device timestamps), which we don't use at the moment.
> Use snd_pcm_avail_update

- src/host/alsa/mod.rs
Not setting the buffer size can cause an overlarge buffer to be used. This can causes noticeable audio delays. See #307 discussion.
> Alsa: Set buffer size near to 100ms

- Cargo.toml
- examples/feedback.rs
As mentioned on the Rust Audio discord, the `feedback` example should use a ringbuffer instead of mpsc channels
> Uses ringbuffer in feedback example

- src/error.rs
- src/lib.rs
Trying to slim down the `lib.rs` file a bit.
> Move errors into separate module

- Cargo.toml
When using cpal as dependency in other project, it was found that cpal
won't build due to unresolved import of winapi::um::winbase. Added the
feature at line 24 in Cargo.toml.
Edit) My OS was Windows 10, and Rust toolchain was like below:
stable-x86_64-pc-windows-msvc (default)
rustc 1.38.0 (625451e37 2019-09-23)
> Added winapi feature "winbase" in windows dependencies

- Cargo.toml
- examples/beep.rs
- examples/enumerate.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/error.rs
- src/lib.rs
Currently CPAL only really uses `failure` for its `derive` capabilities
and the ability to easily generate implementations for `Display`. That
said there are a few issues with using the `failure` crate:
- `failure` does not provie a `std::error::Error` implementation without
first converting error types into `failure::Error`.
- It leaks significantly into the public API and expects downstream
users to also depend on `failure` and the non-std `Fail` trait for
their own error handling.
- Solved problems such as downcasting of causal errors which have since
been addressed in `std`.
- Provides application-friendly `Fail` trait and `failure::Error` type,
not particularly useful to libraries like CPAL.
The [`thiserror` crate](https://github.com/dtolnay/thiserror) is better
targeted towards …
> Switch to dtolnay's `thiserror` for handling error boilerplate

- src/host/wasapi/device.rs
- src/host/wasapi/mod.rs
- src/host/wasapi/stream.rs
This works by detecting output devices in build_input_stream() and
setting the AUDCLNT_STREAMFLAGS_LOOPBACK flag to enable loopback
recording.
closes #251
> Implement WASAPI loopback support

- .github/workflows/cpal.yml
In this way, `cargo-publish` shouldn't view them
> Move error files into another directory

- CHANGELOG.md
- Cargo.toml
Please see the CHANGELOG diff for an overview of changes included in this
release.
You can find the full code diff [here](https://github.com/RustAudio/cpal/compare/391b32f5b2704141506eb4fcb827b8de76e77d54...master).
Thanks to all who have contributed! CPAL has come a long way thanks to
the combined effort of many different people!
> Publish version 0.11.0

- src/lib.rs
I noticed that these links on the [main documentation page](https://docs.rs/cpal/0.11.0/cpal/) point to the wrong urls:
This pull requests updates them (as it seems the `Host`, `Device`, and `EventLoop` objects changed from traits to structs).
> Update struct links in crate documentation

- .gitignore
- Cargo.toml
- asio-sys/src/bindings/mod.rs
- examples/beep.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/host/alsa/mod.rs
- src/host/asio/device.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/mod.rs
- src/host/emscripten/mod.rs
- src/host/null/mod.rs
- src/host/wasapi/com.rs
- src/host/wasapi/device.rs
- src/host/wasapi/mod.rs
- src/host/wasapi/stream.rs
- src/lib.rs
- src/platform/mod.rs
- src/traits.rs
This PR is a rebase of @ishitatsuyuki's work in #301. Originally opened at ishitatsuyuki/cpal#3 but closed in favour opening a new PR here.
*Edit: This bug seems to have been addressed in the rebase*.
After testing each of the examples with the ALSA backend on my Arch Linux system, I noticed that the `feedback.rs` example no longer works. No audio output was occurring and after some investigation it seems the output stream callback only seems to get called once. `beep.rs` and `record_wav.rs` both work fine, which leads me to wonder if there's an issue with the way multiple streams are being handled. `feedback.rs` also works fine on `master`, so this has likely been introduced in this PR.
@ishitatsuyuki does anything come to mind as a potential cause for this? I did notice that we're now …
> Removing the `EventLoop` - rebased

- asio-sys/Cargo.toml
- asio-sys/src/bindings/mod.rs
- examples/beep.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/host/alsa/mod.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/mod.rs
- src/host/emscripten/mod.rs
- src/host/null/mod.rs
- src/host/wasapi/device.rs
- src/host/wasapi/stream.rs
- src/lib.rs
- src/platform/mod.rs
- src/samples_formats.rs
- src/traits.rs
This is an implementation of the planned changes described in #119.
For a quick overview of how the API has changed, check out the updated
examples.
**TODO:**
- ~Remove `data_type` field from `Format`? See [here](https://github.com/RustAudio/cpal/issues/119#issuecomment-573788380).~
- Update backends:
Closes #119
Closes #260
> Remove `UnknownTypeBuffer` in favour of specifying sample type.

- examples/beep.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/host/alsa/mod.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/mod.rs
- src/host/emscripten/mod.rs
- src/host/null/mod.rs
- src/host/wasapi/device.rs
- src/lib.rs
- src/platform/mod.rs
- src/traits.rs
Fixes #119. ~Seeking feedback before proceeding.~ As discussed in #359, this provides a statically-typed buffer to the user without incurring additional monomorphization cost.
TODO:
- ~Privatize `Data`~
> Polymorphic streams

- examples/beep.rs
- examples/enumerate.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/error.rs
- src/host/alsa/mod.rs
- src/host/asio/device.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/enumerate.rs
- src/host/coreaudio/mod.rs
- src/host/emscripten/mod.rs
- src/host/null/mod.rs
- src/host/wasapi/device.rs
- src/host/wasapi/mod.rs
- src/lib.rs
- src/platform/mod.rs
- src/traits.rs
This implements the changes described at #370.
Closes #370.
Backends implemented:
Edit: here is the full list of renamings to make it easier for downstream crates to adapt:
- `Format` type's `data_type` field renamed to `sample_format`.
- `Shape` -> `StreamConfig` - The configuration input required to build a stream.
- `Format` -> `SupportedStreamConfig` - Describes a single supported stream configuration.
- `SupportedFormat` -> `SupportedStreamConfigRange` - Describes a range of supported configurations.
- `Device::default_input/output_format` -> `Device::default_input/output_config`.
- `Device::supported_input/output_formats` -> `Device::supported_input/output_configs`.
- `Device::SupportedInput/OutputFormats` -> `Device::SupportedInput/OutputConfigs`.
- `SupportedFormatsError` -> …
> Rename stream `Format` types to `StreamConfig` and other related renamings.

- CHANGELOG.md
Just realised that we've been missing updates CHANGELOG updates in PRs. I wonder if we should add a PR template that has a reminder?
> Update changelog for changes since 0.11

- asio-sys/build.rs
- build.rs
- examples/record_wav.rs
Specifying the static lifetime in constants and static variables
is redundant since Rust 1.17.0
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1170-2017-04-27
> Remove redundant 'static from &'static str

- src/host/alsa/mod.rs
I built a small audio app on the raspberry pi zero w, and got an error during the build:
```
error[E0308]: mismatched types
--> /home/pi/.cargo/git/checkouts/cpal-c2179e82da06da7e/f3e7c46/src/host/alsa/mod.rs:766:22
|
766 |         if result == -libc::EPIPE as i64 {
|                      ^^^^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
|
help: you can convert an `i64` to `i32` and panic if the converted value wouldn't fit
|
766 |         if result == (-libc::EPIPE as i64).try_into().unwrap() {
|                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
error: could not compile `cpal`.
```
Here, `result` comes from the `snd_pcm_writei()` function which returns a `long`. On the ARM …
> Fix type for armv6 platforms

- .github/workflows/cpal.yml
The `alsa-sys` crate repository has lived [here][1] for quite a while.
This commit removes the unnecessary step from the CI workflow now that
alsa-sys has finally been removed as of #386.
[1]: https://github.com/diwic/alsa-sys
> Remove alsa-sys publish step from cpal publish github workflow

- src/host/alsa/mod.rs
This PR leaves the buffer time unrestricted if restricting it failed. Failure will only happen with buggy alsa drivers, so this allows users with those drivers (e.g. me :P) to use projects built on `cpal`. It should have no impact on users where the function succeeds.
> Recover if hw_params_set_buffer_time failed.

- .github/workflows/cpal.yml
- CHANGELOG.md
- examples/beep.rs
- examples/feedback.rs
- examples/record_wav.rs
- src/host/alsa/mod.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/mod.rs
- src/host/emscripten/mod.rs
- src/host/null/mod.rs
- src/host/wasapi/device.rs
- src/host/wasapi/stream.rs
- src/lib.rs
- src/platform/mod.rs
- src/traits.rs
I began on an implementation of the timestamp API described in #363 but
quickly realised that it might be best to land the API for providing
extra information to the user's callback first.
This PR adds two new types: `InputCallbackInfo` and `OutputCallbackInfo`.
These types are delivered to the user's data callback as a new, second
argument.
While these types are currently empty, the intention is for these types
to provide information relevant to the current request for or delivery
of data. This includes:
- Timestamp information #363.
- Flags related to the state of the stream (e.g buffer
underflow/overflow, [priming output](http://www.portaudio.com/docs/v19-doxydocs/portaudio_8h.html#ad6616980c2259866a39eb2b76fa4697d), etc).
- Anything else we deem necessary in the future.
In order to …
> Add a `CallbackInfo` argument to the stream data callback

- Cargo.toml
- asio-sys/src/bindings/mod.rs
- src/host/alsa/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/mod.rs
- src/host/emscripten/mod.rs
- src/host/wasapi/device.rs
- src/host/wasapi/stream.rs
- src/lib.rs
This PR addresses #363. 
Currently, the PR only contains the top-level API but does not yet provide an implementation for each of the hosts. I'm posting this early in order to allow for feedback before diving too deeply into the implementation for each host.
- Platforms:
- ~null~ N/A
> [WIP] Timestamp and `StreamInstant` APIs

- .github/workflows/cpal.yml
- Cargo.toml
- src/host/emscripten/mod.rs
- src/host/mod.rs
- src/host/webaudio/mod.rs
- src/lib.rs
- src/platform/mod.rs
This rebases @dpeckett 's awesome work on #372, addressing the recent changes introduced by #397, #395, and #371 in the process.
TODO:
> Rebase/Update webaudio PR for recent breaking changes

- src/host/coreaudio/mod.rs
Hi, discovered 7 warnings issued by `rustc 1.42.0 (b8cedc004 2020-03-09)`.
`cargo build` and `cargo test` run successfully with the changes in this PR.
The list of warnings fixed:
1. warning: unnecessary `unsafe` block [L184]
2. warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string() [L330, L817, L831, L846]
3. warning: field is never read: `device_id` [L411]
> Fix CoreAudio warnings.

- src/host/webaudio/mod.rs
The `supported_stream_configs` method now returns the range of
configurations that are required to be supported for
`BaseAudioContext.createBuffer()` as mentioned here:
https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createBuffer
That is, valid stream configurations are now considered to be any
configuration that has:
- 1 <= channel_count <= 32 and
- 8khz <= sample_rate <= 96khz
- sample_format == f32
Closes #410.
Closes #411.
> Add implementation of supported stream configs for webaudio

- src/host/alsa/mod.rs
When I tried cross compiling the source on git to `armv7-unknown-linux-gnueabihf`, it errors with 
```
error[E0308]: mismatched types
--> /home/user/cpal/src/host/alsa/mod.rs:786:40
|
786 |     ts.tv_sec as i64 * 1_000_000_000 + ts.tv_nsec
|                                        ^^^^^^^^^^ expected `i64`, found `i32`
error[E0277]: cannot add `i32` to `i64`
--> /home/user/cpal/src/host/alsa/mod.rs:786:38
|
786 |     ts.tv_sec as i64 * 1_000_000_000 + ts.tv_nsec
|                                      ^ no implementation for `i64 + i32`
|
= help: the trait `std::ops::Add<i32>` is not implemented for `i64`
```
casting `ts.tv_nsec` to `i64` seems like the easiest fix.
> Fix build error when cross compiling

- Cargo.toml
This should reduce the footprint of cpal on non-windows platforms.
> Move dependencies unused on non-windows platforms to the windows section in Cargo.toml

- .github/workflows/cpal.yml
To allow pushing to master after the 0.12.0 release.
The 0.12.0 release will be uploaded manually.
> Disable cargo publish invocation

- .github/workflows/cpal.yml
The manual release of 0.12.0 is done.
Hopefully the issue is now resolved and in the future the CI can do it automatically.
cc #428 and #444
> Reenable the publish github workflow

- src/host/alsa/mod.rs
- src/lib.rs
Hi there,
This patch adds some basic test coverage for the above function.
It also includes a tiny change adding an `#[allow(dead_code)]` to kill a compilation warning in the ALSA module.
> Add test coverage for cmp_default_heuristics

- src/host/alsa/mod.rs
`alsa::pcm::Frames` resolves to `c_long` which is 32 bits instead of 64 when compiling for raspberry pi (armv7l).
> Use alsa::pcm::Frames in alsa API calls instead of fixed-width integers.

- README.md
I wrote a simple getting started guide for creating a CPAL WASM project that I published to the Wiki. It was adopted from the existing work of @ishitatsuyuki . [See this link](https://github.com/RustAudio/cpal/wiki/Setting-up-a-new-CPAL-WASM-project)
I didn't see a way to create PR for a post in the Wiki so if anyone has any issues they want to be addressed with the post just let me know here.
> adding in a link to the CPAL WASM guide into the Readme

- src/host/emscripten/mod.rs
- src/host/webaudio/mod.rs
Fix the behaviour of wasm `default_output_device()` based on the documentation [here](https://github.com/RustAudio/cpal/blob/master/src/lib.rs#L570), and in-browser testing
> webaudio: Fix default_output_config

- src/host/alsa/mod.rs
This fixes an issue I was running into where when an underrun happened on the output buffer, the output stream worker would get stuck in a loop using up 100% cpu polling the descriptors and audio playback would stop.
> Handle ALSA overruns/underruns by resetting the PCM device

- .github/workflows/cpal.yml
- Cargo.toml
- README.md
- src/host/mod.rs
- src/host/oboe/android_media.rs
- src/host/oboe/convert.rs
- src/host/oboe/input_callback.rs
- src/host/oboe/mod.rs
- src/host/oboe/output_callback.rs
- src/platform/mod.rs
This code compiles (assuming my PR into `oboe-rs` gets merged), but has not been tested yet, because there are problems with including multiple .so in a single .apk (https://github.com/katyo/oboe-rs/issues/5). In the meantime I'd like to ask for clarifications for a couple of questions that occurred during implementation:
1. `StreamInstant` for callbacks.
It's unclear whether CPAL guarantees any relations between different `StreamInstant` values. For example, should `callback` and `capture` fields of `InputStreamTimestamp` be comparable in any way? Should `InputStreamTimestamp` values for different streams be comparable?
Oboe provides only the number of frames read/written from/to the stream. Based on the number of frames and sample rate it's possible to compute the duration. This is how …
> Android support via Oboe

- src/host/wasapi/device.rs
See issue #476.
This is essentially PR #339 again which was merged but was later (accidentally?) removed again.
It allows loopback capture from a WasApi output device.
> Re-enable WasApi loopback capture

- build.rs
- src/host/coreaudio/enumerate.rs
- src/host/coreaudio/mod.rs
- src/lib.rs
- src/samples_formats.rs
Clippy insists on checking all dependencies to my project, so I'm motivated to eliminate its warnings. Most of Clippy's recommendations here are stylistic, but one identifies a potential bug: in src/host/coreaudio/mod.rs line 660, there is a loop waiting for changes to the variable "reported_rate," which can only happen because of an unsafe alias earlier in the method. A compiler might optimize away the loop.
> Eliminate or suppress Clippy messages.

- src/lib.rs
Affects the "How to use cpal" section on the main page of the docs.
Point the `Stream` link to the `struct Stream` following the example
of the `Device` and `Host` links from the same section.
> Fix broken Stream concept link in the docs.

- .github/workflows/cpal.yml
- Cross.toml
- Dockerfile
This PR is inspired by https://github.com/RustAudio/cpal/issues/473. 
It adds an action to run cargo check and test for the 32-bit armv7 arch. 
First it builds a docker container, by starting from `rustembedded/cross:armv7-unknown-linux-gnueabihf` and adding all dependencies. Then it uses `cross` (https://crates.io/crates/cross) to run check and test.
> Add CI for linux on armv7 (32bit)

- Cargo.toml
- src/host/alsa/enumerate.rs
- src/host/alsa/mod.rs
Some low-level ALSA devices seem to not react well to having `snd_pcm_open()` called immediately after `snd_pcm_close()` on another handle for the same device. See for example this StackOverflow [answer](https://stackoverflow.com/questions/4474858/alsa-opening-and-closing-pcm-on-the-fly#answer-4474959).
Currently enumerating ALSA devices will cause each device to be opened and immediately closed, as will calling `supported_configs()`. Finally, the device is only opened for good when `build_*_stream_[raw]()` is called.
This patch ensures that `alsa::PCM::new()` is called only once for a given `Device` by saving each `PCM` object in the `Device` instance the first time it is opened and then handing ownership off to the `Stream` when it is created. A `parking_lot::Mutex` is used to provide …
> Avoid calling alsa::PCM::new() multiple times.

- .github/workflows/cpal.yml
- Cargo.toml
- examples/android.rs
- examples/beep.rs
- examples/enumerate.rs
- examples/feedback.rs
- examples/record_wav.rs
Since the Android target was added, the examples have been building as cdylibs instead of binaries. This obviously makes testing more difficult on platforms that are not Android. This PR creates a copy of the beep example specifically for building as an Android APK and sets the remaining examples back to a crate-type of bin.
This PR also adds argument parsing (using structopt) to several of the examples to allow selecting non-default devices and (for the feedback example) setting the latency. Finally, it improves error handling in the enumerate example in the case that supported_input_configs() or supported_output_configs() returns an error.
These changes make it easier to test cpal on systems with multiple audio devices.
> Examples improvements

- Cargo.toml
- src/host/alsa/mod.rs
This was introduced in `6b91485` and it caused issues with some alsa
configurations like with `pipewire-alsa` for me which caused the audio to be
become weirdly distorted.
> Fix alsa in some configs outputting bad audio

- README.md
The readme doesn't mention JACK support which was merged a while ago (#389).
Fixes #529
> Add JACK support to README

- Cargo.toml
- src/host/jack/stream.rs
With rust-jack 0.7, the buffer_size callback is moved to ProcessHandler. This reflects how it is actually called by jack: it is called synchronously on the process thread, but it is allowed to perform non-real-time-safe operations. In CPAL, this means that it is fine to reallocate the temporary interlacing buffers when buffer size changes.
This removes the need for buffer splitting on the output stream type, and prevents panics when buffer size is made larger than it was initially on the input stream type. (for some reason, buffer splitting was not implemented for input previously)
More info: https://github.com/RustAudio/rust-jack/issues/137
> Update to rust-jack 0.7 and simplify implementation

- src/host/alsa/mod.rs
Rebased by @strohel . Rebased version of #520.
* Always set period before setting buffer size, even if
`BufferSize::Fixed`.
* Set `start_threshold` based on `alsa::Direction` to avoid underruns on
playback streams.
Also refactor the return values of the set params functions to reflect their
actual use and resolve some clippy warnings (including a logic error in
`stream_timestamp()`).
> [ALSA] Improve stream setup parameters.

- src/host/wasapi/com.rs
COM can prevent undefined behavior in either concurrency model by
performing marshaling when necessary. As a result, CoInitializeEx can be
called with either concurrency model, and in this case STA provides better
compatibility with other code requiring STA, e.g. ASIO backend or winit
drag-and-drop.
To dive into the detail, the entry point of WASAPI, MMDeviceEnumerator, is
registered with "both" threading model, which means that COM objects are
created with whatever the thread's concurrency model is set to. This raises
the concern that when STA is used, marshaling might make audio buffer
operations block on the main thread, breaking continuous audio processing.
However, the implementation actually uses free-threaded marshaller for
interfaces dealing with buffer operations, which …
> wasapi: Allow both threading models and switch the default to STA

- src/host/asio/stream.rs
In ASIO, input and output buffers need to be created at the same time.
So `Driver::prepare_output_stream` takes infos of already exist input.
But `Device::get_or_create_output_stream` was passing infos of exist output.
This breaks already exist input stream.
`Device::get_or_create_intput_stream` was fine, passing infos of exist output.
> Fix ASIO driver.prepare_output_stream should take streams.input

- Cargo.toml
Bump `oboe`, `ndk` and `ndk-glue` dependency versions.
> Bump android dependencies

- Cargo.toml
- examples/synth_tones.rs
Sample-based generation of sound.
It is refactored version of the example `beep`. I bubbled up a callback to generate a sample. Also, I replaced `unwrap` with proper handling of errors. That does not add complexity because `anyhow` and `?` are already in use. That's the first step I would like it was done for me to start playing with `cpal` and integrating it into my projects. 
Hopefully, it will be useful for not only me.
#613
> Add sample-based generation example: synth_tones

- src/host/alsa/mod.rs
Questions:
- The start threshold actually *does* matter in capture streams: when we hit `PollDescriptorsFlow::XRun`, we prepare the device but don't start it explicitly. Should we do so? (it doesn't make much of a difference in practice, since we read immediately from input streams... except we don't, we poll them! Is this a CPAL bug where input streams never restart after xrun?!)
- I tried testing xrun. But when I suspend the cpal process (feedback talking to pipewire-alsa) with Ctrl+Z, then fg a second later, it somehow doesn't hit xrun. This even happens if I add a 500ms sleep in the loop of `input_stream_worker()`!
- And cpal feedback `cargo run --example feedback -- front:CARD=Generic,DEV=0 front:CARD=Generic,DEV=0` won't detect `front:CARD=Generic,DEV=0` as an output device, only …
> Cleanup and document cpal's ALSA backend

- Cargo.toml
Is there anything that blocks from bumping the `cpal` version? We are struggling with `ndk-glue` collision errors, and it would be great to release a new `cpal` version to get rid of them.
> Bump cpal crate version to 0.13.5

- Cargo.toml
- src/host/oboe/android_media.rs
`ndk-glue` suffers one fatal flaw: it's "only" supposed to be used by the crate providing `fn main()` and only supposed to end up in the dependency graph once as it has `static` globals which get duplicated across versions.
In the current case with `winit 0.26` still on `ndk-glue 0.5` but `cpal` on `ndk-glue 0.6` it'll always panic in `fn native_activity()` as the `static` globals on this version is not initialized.
Introducing `ndk-context`: a crate that holds these `static`s, with the intention/premise to not see a breaking release /ever/ and make this a problem of the past.  The crate is currently initialized with the VM and Android Context on `ndk-glue` 0.5.1 and 0.6.1 (0.4.1 pending) making it compatible with whatever is current, and the possibility for backporting to older …
> android: Migrate from `ndk-glue` to `ndk-context`

- Cargo.toml
- src/host/alsa/enumerate.rs
- src/host/alsa/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/ios/enumerate.rs
- src/host/coreaudio/ios/mod.rs
- src/host/coreaudio/macos/enumerate.rs
- src/host/coreaudio/mod.rs
- src/host/emscripten/mod.rs
- src/host/jack/device.rs
- src/host/jack/mod.rs
- src/host/jack/stream.rs
- src/host/null/mod.rs
- src/host/wasapi/mod.rs
- src/host/webaudio/mod.rs
- src/traits.rs
The api between clap 3.0 and 3.1 as change and make the test uncompilable.
> Rust 2021 and clap 3.0

- src/platform/mod.rs
With the upcoming PipeWire backend the macros for Linux start to look a bit messy (O(2^n) scaling), so let's implement a solution that fix that clutter.
> platform: Conditional impl_platform_host based on feature flags

- examples/feedback.rs
- examples/record_wav.rs
both feedback.rs and record_wav.rs have "bleep" as their application name when constructing `clap::Command`. This commit changes the constructor argument for each example to match their filenames.
> Fix example typos

- src/platform/mod.rs
The conversion between platform specific structs to platform-agnostic ones is already implemented, but the reverse path does not exist.
To allow that, this PR exposes `DeviceInner`, `DevicesInner`, `HostInner` and `StreamInner` (structs that already existed before), by the methods `as_inner`, `as_inner_mut` and `into_inner`.
Other possible implementation would be replacing each struct by its own inner (like replace `Device` by `DeviceInner`), but this was not possible because of the `Stream` struct that contains a seconds field.
Another one would be to make the inner field public (i.e. field `0` in the current implementation), but this may guarantee better documentation and forward compatibility. And, to be honest, I only think of that possibility while writing this comment.
If you prefer …
> Expose underlying platform specific implemenations

- src/host/webaudio/mod.rs
On Chrome, If a `AudioContext` is created before a user interaction, it starts in `suspended` state. To resume it, I must call `AudioContext.resume()`. For more information: https://developer.chrome.com/blog/autoplay/
To allow that, this PR exposes the `AudioContext` of `WebAudioStream`.
Related to #49.
> WebAudio: expose AudioContext in WebAudioStream

- Cargo.toml
- asio-sys/Cargo.toml
- asio-sys/src/bindings/mod.rs
- asio-sys/src/lib.rs
- src/host/wasapi/device.rs
- src/lib.rs
Updates all of the dependencies that are currently outdated and switches lazy_static to once_cell. Fixes #670.
> Update dependencies, switch to once_cell

- src/host/oboe/mod.rs
In some cases, device with index 0 is NOT the default output device - in my case it happens to be the ear speaker. Returning Device(None) there makes Oboe choose the default input/output device - everything works as expected.
> fix: Android - Return Device(None) as a default i/o device

- Cargo.toml
- src/host/wasapi/com.rs
- src/host/wasapi/device.rs
- src/host/wasapi/mod.rs
- src/host/wasapi/stream.rs
I migrated to `windows-rs` in this PR since exposing the buffer size range for hardware-offloaded audio processing requires `IAudioClient2`, which isn't exposed in the `winapi` crate, and `winapi` seems to be more or less unmaintained at this point.
Regarding fixed buffer sizes - `wasapi` doesn't seem to support requesting *exact* audio buffer sizes, but will always get an audio buffer that is at least the size requested. Should that be mentioned in the documentation? Also, the buffer exposed to the `data_callback` doesn't always match the size of the buffer requested, since `wasapi` incrementally updates the buffer as audio gets played, instead of updating it all at once once the buffer is cleared. I'm not sure if that's standard behavior or not but it may also be worth documenting. …
> Implement BufferSize::Fixed in wasapi, and migrate wasapi to officially-supported Windows crate

- src/host/alsa/mod.rs
- src/host/asio/device.rs
- src/lib.rs
Looks like there were some left-overs from the 2021 migration which this PR tries to fix.
I also sneaked in the removal of some dereferences and inconsequential implementation of `Partial/Eq` clippy was complaining about.
see also: https://github.com/RustAudio/cpal/pull/689#issuecomment-1250383218
> Fix some Edition 2021 warnings/errors

- .github/workflows/cpal.yml
This PR removes the old and complex way to publish `cpal` on crates.io with a much simpler action
> Use an action to publish the crate

- .github/workflows/cpal.yml
This option ignores unpublished changes and remove useless options
> CI: Ignore unpublished changes for the publish action

- Cargo.toml
- examples/android.rs
- examples/beep.rs
- examples/record_wav.rs
- examples/synth_tones.rs
- src/host/alsa/mod.rs
- src/host/asio/device.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/oboe/input_callback.rs
- src/host/oboe/mod.rs
- src/host/oboe/output_callback.rs
- src/host/wasapi/device.rs
- src/host/wasapi/stream.rs
- src/lib.rs
- src/samples_formats.rs
- src/traits.rs
This is an attempt to fix https://github.com/RustAudio/cpal/issues/488
In the course of migrating to `dasp_module` I also unlocked `i8`, `u8`, `i32`, `u32`, `i64`, `u64` and `f64`. I did not extend this to `i24`, `u24`, `i48`, `u48` because I felt there are open question regarding the memory layout.
So far I did run the tests for ALSA. I might need some help to adjust the implementation for other platforms.
> migrate Sample to dasp_sample

- Cargo.toml
- src/host/coreaudio/macos/mod.rs
- src/host/coreaudio/macos/property_listener.rs
- src/host/coreaudio/mod.rs
Relates to #704 and #373.  Implements a very basic mechanism for polling to determine if the device underlying a CoreAudio-backed stream has been disconnected.  This definitely works, but is obviously a very platform-dependent solution as you have to unpack the underlying stream type to access it.
Feedback extremely welcome.  The main thing I'm dissatisfied with here is that we must poll to determine if the device has dropped to then trigger some action.
> Implement disconnection detection for CoreAudio on MacOS.

- examples/android.rs
- examples/beep.rs
- examples/feedback.rs
- examples/ios-feedback/src/feedback.rs
- examples/record_wav.rs
- examples/synth_tones.rs
- examples/wasm-beep/src/lib.rs
- src/host/alsa/mod.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/ios/mod.rs
- src/host/coreaudio/macos/mod.rs
- src/host/emscripten/mod.rs
- src/host/jack/device.rs
- src/host/null/mod.rs
- src/host/oboe/mod.rs
- src/host/wasapi/device.rs
- src/host/webaudio/mod.rs
- src/lib.rs
- src/platform/mod.rs
- src/traits.rs
This makes it possible for the library client to handle situations where the host takes too long to respond or even blocks forever, eg. a retry can be applied.
if the timeout passed is "None" the current behaviour is applied, eg. blocking forever. if the timeout passed is a Duration then it will be applied to the Device Streams. This is only implemented for ALSA, the other hosts will ignore the parameter for now.
Signed-off-by: Marc Bodmer <marc.bodmer@securiton.ch>
> add timeout paramter to DeviceTrait stream builders

- .github/workflows/cpal.yml
- Cargo.toml
- examples/beep.rs
- examples/feedback.rs
- examples/record_wav.rs
Bumps most linux dependencies. Moves examples to clap 4.0 and changes them to use clap_derive. This simplifies the examples and let them focus on the real content they offer.
> Bump linux deps, simplify examples, remove nix dep

- Cargo.toml
- src/host/emscripten/mod.rs
- src/lib.rs
- src/samples_formats.rs
This is the replacement PR for #519. Fixes #518 
Replaces stdweb dependency, which is unmaintained, with web-sys, js-sys, and wasm-bindgen for the emscripten OS.
This should be close to working, but I'll have to see if the test suite passes after this retry of the old PR.
> Remove stdweb in favor of js-sys, web-sys, and wasm-bindgen

- src/error.rs
- src/lib.rs
- src/platform/mod.rs
- src/traits.rs
There are a couple of places where the links may be a little bit ugly in the source, but I opted to keep them when appropriate because the usability improvement on the docs page is pretty nice. The worst offenders have their links put as references at the bottom of the block, but I tried to be sparing with this because it's a bit more annoying to maintain.
While this would probably be enough to close #650, note that this only targets `cpal` and not the contained `asio-sys`.
> Add rustdoc links in most of the documentation

- examples/wasm-beep/package-lock.json
- examples/wasm-beep/package.json
- examples/wasm-beep/webpack.config.js
**Problem:** The `wasm-beep` example fails to run on Windows, giving the error "digital envelope routines unsupported". 
**Solution:** Upgrading Webpack from 3.* to 5.* resolved the error.
> Note: This PR requires the "syncWebAssembly" option. The latest Wasm spec recommends "asyncWebAssembly" instead, but the Rust code would have to be updated to use this.
**Testing:** Successfully tested `npm install`/`npm run`/`npm run build` on Windows and Mac.
I also updated the Wiki here: https://github.com/RustAudio/cpal/wiki/Setting-up-a-new-CPAL-WASM-project
> Fix wasm-beep example on Windows by upgrading to Webpack 5

- .github/workflows/cpal.yml
- examples/wasm-beep/src/lib.rs
Fixes #721 
Changes to a dependency library broke compilation of the example. Changes needed to get the example working and warning-free include:
1. specifying additional type constraints in local implementations
2. using the `FromSample` trait to convert samples in the handler
3. adding a default matcher in response to the non-exhaustive attribute on `SampleFormat`
> Fix compile issues in wasm-beep example

- Cargo.toml
- src/host/coreaudio/macos/mod.rs
https://github.com/RustAudio/coreaudio-rs/compare/1de4dc04a858dba3bc1b170ce980ee2e2825f864..163f1a09f0afdc80b01f3cba8956c207aa3a1cbd
Tentative, just updating the version & API usage.
This PR will bring a bug fix on `coreaudio-rs` (https://github.com/RustAudio/coreaudio-rs/pull/91)
> Update to use coreaudio-sys 0.11

- CHANGELOG.md
- Cargo.toml
- src/host/wasapi/com.rs
- src/host/wasapi/device.rs
- src/host/wasapi/stream.rs
It would be nice to get the windows crate dependency updated to the latest version to avoid duplicated dependencies like this one: https://github.com/bevyengine/bevy/actions/runs/3451394906/jobs/5760584454
This is my attempt to help with that. Feedback is welcome!
A lot of the changes were just changing null pointer arguments to None which should be straightforward. 
There are a couple places I don't fully understand the consequences and just did what I needed to satisfy the type checker. If anyone more familiar with FFI and/or the Windows API can confirm it looks correct that would be much appreciated.
Especially around this section here with the pointer to a pointer, that was definitely something I don't deal with often: https://github.com/paul-hansen/cpal/blob/1c1c29ea1b627e433b5dea4734 …
> Update `windows-rs` dependency

- Cargo.toml
It is not used directly, only reexported version from alsa
Direct use of `nix` crate was removed back in 214403f
> Cargo.toml: drop dependency on nix

- src/host/asio/device.rs
- src/host/asio/stream.rs
Hi, I was testing out asio and to get it working with ASIO I had to make these changes to allow ASIO to use i32.
I think the comment explaining why `ASIOSTInt32` is mapped to `SampleFormat::I16` is not relevant any more seeing as `SampleFormat::I32` has been added.
Note:
I also had to apply https://github.com/RustAudio/cpal/pull/626 to get cpal to work without segfault.
> Support i32 for asio

- src/host/wasapi/device.rs
It was changed incorrectly in https://github.com/RustAudio/cpal/pull/726
> Fix CoTaskMemFree always getting called with null

- Cargo.toml
- README.md
This PR exposes oboes shared-stdcxx feature from cpal. Access to this was required for us to fix builds on a couple android targets
> make oboe's shared-stdcxx feature accessible

- Cargo.toml
- src/error.rs
- src/lib.rs
This PR removes the `thiserror` dependency, and replaces it with handwritten Error implementations.
The goal of this PR is to remove some dependencies and to shorten compile times for downstream crates, to which `thiserror` contributes a fair amount since it's a proc-macro. On my computer this brings the cold release build time down from 14s to 9s!
While removing `thiserror` does add back some boilerplate that is annoying to write, it is still quite easy to read through, and it is also isolated in the `error` module where it doesn't impact any logic code. I think the maintainability impact is minimal, while the compile times and dependency bloat improvements are quite solid. :slightly_smiling_face:
> Remove thiserror and replace it with handwritten Error impls

- asio-sys/build.rs
- build.rs
If this isn't done, then a `cargo clean` is required to toggle asio support on and off.
> Re-run build script if CPAL_ASIO_DIR changes or the folder it points to does

- Cargo.toml
- src/host/coreaudio/mod.rs
crate `mach` is unmaintained and hasn't been updated in 4 years https://github.com/fitzgen/mach/issues/63
crate `mach2` is now the updated version https://github.com/JohnTitor/mach2
This works the same on my Mac 👍
> switch from mach to mach2

- src/host/wasapi/stream.rs
- when main(or other) thread(s) tries to drop Stream object, it would panic at [host/wasapi/stream.rs Stream::drop()](https://github.com/RustAudio/cpal/blob/e5ccc46afa4a420421c54f513dcd0ccd0202d70e/src/host/wasapi/stream.rs#L164) if wasapi thread is dead. 
- it's problematic when the user wants to do something after all the cpal objects have been dropped.
- main(or other) thread(s) can't know if wasapi thread's alive or dead.
Let's add a return value to `push_command()`, and handle the errors where it is called.
> Fixed wasapi thread panics involving the main(or other) thread(when Stream drops).

- Cargo.toml
- src/host/wasapi/device.rs
The current version of `cpal` requires Rust `1.64` to compile on Windows. This updates the `windows` dependency, which hopefully reduces the MSRV again because of https://github.com/microsoft/windows-rs/pull/2318.
> bump windows dependency to 0.46

- src/platform/mod.rs
This fixes issue #589.
This warning makes is such that if a function returns a Stream it gives a warning if the stream is not assigned.
It also works for `Result(Stream, Box<dyn Error>)` so using the `?` operator will still give a warning about an unused stream even if the result is unwrapped.
The is an abbreviated example:
```rust
fn run<T>(device: &Device, config: &StreamConfig) -> Result<Stream, Box<dyn Error>>{
let stream = device.build_output_stream(
config,
next_value,
err_fn,
None,
)?;
stream.play()?;
Ok(stream)
}
let main() -> Result<(), Box<dyn Error>> {
let _stream = run(&device, &config)?; // will work and will output sound until `_stream` is dropped
// Previously didn't do anything on success. Now it will warn that it won't do anything.
run(&device, &config)?;
}
```
> Added must use to stream. Fixes issue #589

- asio-sys/src/bindings/errors.rs
- src/host/asio/stream.rs
From #775 [(comment)](https://github.com/RustAudio/cpal/pull/775#issuecomment-1500953921)
Fixed `asio-sys/src/bindings/errors.rs`
`std::Error::description()` has been deprecated.
It should be replaced with `std::fmt::Display`
I found some code duplication in the `std::fmt::Display` and `std::Error` trait, so I have combined the code in `std::fmt::Display`.
This will be a breaking change, is that OK?
The `std::Error` implementation of `LoadDriverError` and `AsioError` is empty, but I think this is necessary for error handling, so I left it.
Fixed `src/host/asio/stream.rs`
I wondered what to do with the `asio_stream` field, but decided to ignore the warning as it might be there to extend the lifetime.I am not 100% sure that this is the right way to do it.
> Fixed warnings in asio_sys

- CHANGELOG.md
- Cargo.toml
- src/host/wasapi/stream.rs
- src/lib.rs
Just attempting to get Bevy's dependencies to all use the same windows crate version again. Lmk if you want any changes. Thanks!
> Update windows-rs dependency

- examples/synth_tones.rs
Each *_wave() function calls advance_sample(). Having tick() also call it results in skipping every second sample.
Given the name "tick()", one could argue whether advance_sample() rather belongs in this function than in *_wave().
More interesting to me though: I wondered about generative_waveform() trying to build what are fairly simple waveforms out of a finite number of sine waves. It's an interesting demonstration, but it's also (a) an inaccurate approximation (e.g. why stop at the nyquist frequency, vs continuing to 2x or 3x the nyquist frequency? - that does in fact give cleaner results in the time domain), and (b) error prone, as per the triangle wave being wrong.
Here's a graph showing each of the three waveforms currently produced by synth_tones. I've plotted all of them in one …
> Fix synth_tones frequency

- src/host/wasapi/device.rs
This PR is following on to #796 regarding an `assert` in the wasapi layer.
This change just replaces it to bubble a backend specific error with an error message. For our use case, this stops a crash that pops up for some users who encounter this path and allows us to gracefully just not play audio and log a message elsewhere.
Lemme know if there's anything else besides the PR itself that needs adjusting or tending to - and thanks for the great library!
> Replace assert in WASAPI check with bubble'd error

- README.md
- asio-sys/Cargo.toml
- asio-sys/build.rs
Hello all,
Having a rather manual pre build preparation process for the windows ASIO support could be cumbersome for users who'd like to install applications we publish to crates.io which depends on `cpal` by `cargo install` method because `cargo install` builds from source. 
This PR is a suggestion to automate the two steps which is laid out in the [readme.](https://github.com/RustAudio/cpal#asio-on-windows).
- Automate the finding and retrieval of ASIO SDK. 
- Set the build environment by invoking `vcvarsall.bat`
Trying to install LLVM would be out of scope for this script in my opinion because that is more general and essential to have a development environment. If the build fails due to that, normally the user can easily derive the reason from the error message. 
I didn't update the …
> Automate asio sys build

- README.md
- asio-sys/Cargo.toml
- asio-sys/build.rs
- asio-sys/src/bindings/mod.rs
- `vcvarsall.bat` is executed exhaustively for any supported host and target architecture combinations now. 
-  Downloading the ASIO SDK is working on all platforms now which enables cross compilation. 
-  A section on the `README.md` is added which explains cross compilation scenarios for `cpal` with the `asio` feature.
-  `vcvarsall.bat` search is improved greatly to execute smarter and faster to cover for CI scenarios where the disk I/O might be a bottle neck. 
-  A type mismatch bug which was apparent on using the `mingw-w64` tool chain is fixed. 
With these changes I want to enable:
- Better building experience in CI
- Improve existing changes to be cross compilation ready.
What I have tried:
- macOS aarch64 (host) -> windows x86, x86_64 (target) ✅ 
- linux (ubuntu) aarch64 (host) -> …
> Improve asio sys build script

- Cargo.toml
- src/host/wasapi/device.rs
Removes the `once_cell` dependency, using `std::sync::OnceLock` instead.
This bumps the MSRV of the crate from 1.60 to 1.70. Given that #277 is currently unresolved, is this acceptable?
> Remove once_cell dependency

- src/lib.rs
There may be a reason to not do this - but if so, I am not sure what, so just wanted to see if we could add it. This is useful where certain libraries require Copy. For instance, making a radio selector for different config options.
> add Copy for SupportedStreamConfigRange

- Cargo.toml
disable ndk default features
the only default one is `rwh_0.6` which pulls version 0.6 of raw-window-handle but is unused by this crate. removing it let consumers decide which version of the crate they'll depend on
> disable ndk default features

- Cargo.toml
- src/lib.rs
Since `wasm-bindgen` 0.2.88 (which was yanked) and https://github.com/rustwasm/wasm-bindgen/pull/3595, it supports `Option` directly instead of `WasmOption`
> emscripten: directly return Option instead of WasmOption

- src/lib.rs
When trying to select a configuration that is compatible with a specific sample rate, `with_sample_rate` gets a bit clunky because you have to implement the range checking yourself to avoid the panic.
The non-panicking `try_with_sample_rate` is much nicer in comparison.
Before:
```rust
device.supported_output_configs()?
.filter_map(|cfg| if target_rate >= cfg.min_sample_rate() && target_rate <= cfg.max_sample_rate() {
Some(cfg.with_sample_rate(target_rate))
} else {
None
})
```
After:
```rust
device.supported_output_configs()?
.filter_map(|cfg| cfg.try_with_sample_rate(target_rate))
```
> Add non-panicking variant of with_sample_rate

- src/host/webaudio/mod.rs
As the title says this pull request is a minimal change to fix a crash that occurs within `cpal` on the Wasm target when the 'atomics' flag is enabled. This allows `cpal` to be used with multithreaded Wasm / Rust applications.
This change is a small change adapted from this other, significantly larger, pull request: https://github.com/RustAudio/cpal/pull/774.
> Fix crash on Web / Wasm when 'atomics' flag is enabled

- src/host/wasapi/stream.rs
Avoids stuttering in playback when high CPU load.
> Boost WASAPI IO thread priority

- .github/workflows/cpal.yml
The `asmjs-unknown-emscripten` target was removed from upstream, see https://github.com/rust-lang/rust/pull/117338
So remove it from the CI job as well.
> Remove asmjs-unknown-emscripten

- Cargo.toml
- src/host/alsa/enumerate.rs
- src/host/alsa/mod.rs
- src/host/asio/device.rs
- src/host/asio/mod.rs
- src/host/asio/stream.rs
- src/host/coreaudio/macos/mod.rs
- src/host/coreaudio/mod.rs
- src/host/jack/stream.rs
The standard library is using a similar implementation to parking_lot now. Other than APIs that are unstable, there shouldn't be that much of a reason to rely on parking_lot anymore. Parts of the cpal codebase already are using std locks. This PR removes the remaining parking_lot uses and replaces them with the standard library's.
> Remove parking_lot dependency

- src/host/alsa/mod.rs
Fix variable mixup I did in https://github.com/RustAudio/cpal/pull/852 I just spotted.
> Fix minor variable mixup

- examples/beep.rs
- src/host/coreaudio/macos/mod.rs
- src/host/coreaudio/macos/property_listener.rs
- src/host/coreaudio/mod.rs
- src/lib.rs
fix clippy warnings
<details>
```rs
warning: unneeded unit return type
--> src/host/coreaudio/macos/property_listener.rs:11:55
|
11 | struct PropertyListenerCallbackWrapper(Box<dyn FnMut() -> ()>);
|                                                       ^^^^^^ help: remove the `-> ()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit
= note: `#[warn(clippy::unused_unit)]` on by default
warning: unneeded unit return type
--> src/host/coreaudio/macos/property_listener.rs:24:26
|
24 |     pub fn new<F: FnMut() -> () + 'static>(
|                          ^^^^^^ help: remove the `-> ()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_unit
warning: using `clone` on type …
```
> Fix clippy warnings

- asio-sys/Cargo.toml
Bump asio-sys crate to 0.2.2
- Remove one_cell in `asio-sys`. Added call to `ASIOOutputReady`.
- Automate `asio-sys` build.
- Fix aio-sys build failure. Update `bindgen` in `asyo-sys` to 0.64.
> bump asio-sys crate

- .github/workflows/cpal.yml
- Cross.toml
- Dockerfile
Commit message body:
```
See https://github.com/cross-rs/cross/wiki/Configuration#builddockerfile
for context regarding the $CROSS_BASE_IMAGE environment variable. Here, it
resolves toghcr.io/cross-rs/armv7-unknown-linux-gnueabihf:{{cross_version}}
Relies on docker caching instead of pre-building the image.
Cross made the change to the GHCR on https://github.com/cross-rs/cross/pull/609
Add newline at EOF for some files.
```
It could reasonably be considered to remove the dockerfile altogether and declare the 
environment variables [docs](https://github.com/cross-rs/cross/wiki/Configuration#targettargetenv) and apt installation script [docs](https://github.com/cross-rs/cross/wiki/Configuration#targettargetpre-build), [example](https://github.com/cross-rs/cross/wiki/Configuration#build) as …
> ci: Update docker images for arm

- src/samples_formats.rs
Closes #863
[`PartialOrd`] is included as [`Ord`] depends on [`PartialOrd`]
[`PartialOrd`]: https://doc.rust-lang.org/nightly/std/cmp/trait.PartialOrd.html
[`Ord`]: https://doc.rust-lang.org/nightly/std/cmp/trait.Ord.html
> Adds `PartialOrd`, `Ord`, and `Hash` to the `#[derive(...)`] invocation on `SampleFormat`

- src/host/wasapi/device.rs
remove `.clone()` from  `format.buffer_size.clone()` to make clippy happy ;)
```log
warning: using `clone` on type `SupportedBufferSize` which implements the `Copy` trait                                                                                                                     
--> src\host\wasapi\device.rs:455:46
|
455 | ...                   buffer_size: format.buffer_size.clone(),
|                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try removing the `clone` call: `format.buffer_size`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#clone_on_copy
= note: `#[warn(clippy::clone_on_copy)]` on by default
```
> chore: fix a clippy warning

- asio-sys/src/bindings/mod.rs
This may fix failure when enable asio under windows-gnu and windows-msvc build.
https://github.com/RustAudio/cpal/issues/860
> fix: asio failed by timeinfo flags type

- src/host/alsa/mod.rs
For some reason the timestamps returned by ALSA when using the onboard ALC1220 are invalid (0) causing a panic in cpal, crashing my application.
I don't understand ALSA enough to judge why this is happening. This fix only addresses the symptoms by returning an Err instead of panicing. I couldn't find any reason why a panic would be necessary in this case, but might have missed something.
> ALSA: Don't panic when handling invalid stream timestamps.

- Cargo.toml
- src/host/jack/mod.rs
- src/host/jack/stream.rs
Also fixed some minor clippy lints.
> Bump Jack to v0.12

- Cargo.toml
- src/host/jack/stream.rs
Fixes compilation on master when using Jack.
Replaces #914
> JACK: bump to 0.13.0 and fix compliation

- src/host/wasapi/device.rs
Fixed memory leak for parameter ppClosestMatch in call to IAudioClient::IsFormatSupported. Fixes issue #802.
> Fixed WASAPI memory leak

- src/host/coreaudio/macos/mod.rs
This fixes #771 by manually stopping the stream on drop.
> Fix callback being called after dropping the stream

- src/host/alsa/enumerate.rs
- src/host/alsa/mod.rs
- better device name
- list physical devices
- inject most common virtual ones (default, pipewire, pulse, ...)
Replaces #914
Depends on #915 for successful compilation.
> ALSA: better card enumeration

- CHANGELOG.md
- asio-sys/src/bindings/errors.rs
- src/error.rs
Make all error enums `Clone` for convenience.
Context: I'm wrapping most of these in a `thiserror::Error` and not being able to make it `Clone` occasionally makes error management a bit annoying.
> Make all error enums `Clone`

- src/host/wasapi/device.rs
- src/platform/mod.rs
- src/traits.rs
Only WASAPI overrides the default method implementations, other hosts work the same as before (iterating over configs) but they can potentially be optimized later.
Time to get list of WASAPI devices on my machine (5 devices in total) before change: 
Input devices: 12 ms, output devices: 187 ms
After change:
Input devices: 1 ms, output devices: 1 ms
This fixes issue #867
> Added supports_input/output methods to DeviceTrait

- .github/workflows/cpal.yml
See changelog: https://releases.rs/docs/1.84.0/
relevant excerpt:
> Support for the target named wasm32-wasi has been removed as the target is now named wasm32-wasip1. This completes the transition plan for this target following the introduction of wasm32-wasip1 in Rust 1.78. Compiler warnings on use of wasm32-wasi introduced in Rust 1.81 are now gone as well as the target is removed.
> Fix wasi CI not running due to target rename in rust 1.84

- src/error.rs
Needed in rodio to rate-limit the error callback, (we log to stdout and POLLERR was filing up logs & disk space rapidly). Recommended to be implemented by the [rust api guidlines](https://rust-lang.github.io/api-guidelines/interoperability.html).
> derive Eq, PartialEq & Hash for error types

- src/host/alsa/mod.rs
When an ALSA interface ends up in an unrecoverable error state (e.g. device disconnected), the thread that runs `input_stream_worker` (or `output_stream_worker` depending on the type of stream) goes into an infinite loop due to the polling always returning an error.
This infinite loop causes calls to `drop(stream)` to hang indefinitely as the Drop implementation tries to join the polling thread.
By adding a flag that's raised when a `Stream` is dropped, we can add an early exit condition to `poll_descriptors_and_prepare_buffer` that forces a return value of `PollDescriptorsFlow::Return`.
I successfully tested the fix on my local machine by unplugging the microphone while listening to it.
> Fix infinite loop on broken ALSA pipes

- src/host/coreaudio/macos/mod.rs
This patch fixes playing to an an output device other than the default. Such as playing to built-in speakers when headphones are plugged in and the default.
Here is a snippet from the `enumerate` example from before. The error coming from within `audio_unit_from_device` when its `input` parameter was mistakenly `true`.
```
8. "MacBook Pro Speakers"
Error getting supported output configs: BackendSpecific { err: BackendSpecificError { description: "Invalid property value" } }
```
Here is the output of the `feedback` example from before the fix:
```
$ RUST_BACKTRACE=1 cargo run --example feedback -- -i "USB Audio CODEC " -o "MacBook Pro Speakers"
﻿    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.11s
Running `target/debug/examples/feedback -i 'USB Audio CODEC ' -o 'MacBook …
```
> Fix macos non-default audio output

- src/lib.rs
Bumps #899 but uses pubic constructors rather than fields, following the same convention as #679
> Add/make public constructors for InputCallbackInfo, OutputCallbackInfo and StreamInstant 

- src/host/webaudio/mod.rs
- src/lib.rs
> Removing usage of eval

- src/host/aaudio/mod.rs
Migrates https://github.com/RustAudio/cpal/pull/959 to the new NDK/AAudio backend.
> fix: Improve AAudio device names

- src/platform/mod.rs
fix #973
I don't know where you want the `impl` to be placed; I just put it at the bottom of the macro.
> Implement `Default` for `Host`

- src/host/alsa/enumerate.rs
- src/host/alsa/mod.rs
- src/samples_formats.rs
Only fixes for alsa and shared components.
The only controversial one here might be removing the commented-out 24- and 48-bit ints. If anyone has context on that, please let me know.
> Fix clippy lints.

- .github/workflows/cpal.yml
- Cargo.toml
- README.md
- src/host/alsa/mod.rs
- src/host/wasapi/stream.rs
implements #939. As someone who doesn't know a whole lot about cpal's inner workings it looks to me like these are the only threads that the library spawns itself, leading me to think these are the only threads that require manual priority changes. However, `audio_thread_priority` claims to also support MacOS, so maybe someone could look into whether that's applicable here?
I'm not too massive of a fan of `eprintln!` here, however I think the failure should be shown but not prevent the audio thread from running.
I've tested this on my Linux laptop, some verification that this also works for the folks on WASAPI and the BSD's would be nice.
> set realtime priority for stream threads in alsa and wasapi

- src/host/coreaudio/mod.rs
Previously attempting to capture integer-valued audio samples would fail on macOS because that `kAudioFormatFlagIsSignedInteger` flag was not set on the `AudioStreamBasicDescription`.
> Fix handling of integer input formats on macOS

- Cargo.toml
https://github.com/RustAudio/cpal/pull/961 removed the feature flag, which is a shame, because that means the next `cpal` release will be a breaking change. I'd like to get https://github.com/RustAudio/cpal/pull/943 out sooner rather than later (to fix [the issues Bevy and others are experiencing with `bindgen` and the iOS simulator](https://github.com/rust-lang/rust-bindgen/issues/3199)), .
So this PR re-adds the feature flag, but with a comment that it is deprecated.
One could argue that changing the backend itself is a breaking change because of the minimum supported version bump. I will argue that it is not, as there is precedent for such bumps in `rustc` as well, see e.g. [this](https://blog.rust-lang.org/2023/09/25/Increasing-Apple-Version-Requirements/) and …
> Keep deprecated feature flag `oboe-shared-stdcxx` to avoid breaking change

- CHANGELOG.md
- src/host/wasapi/device.rs
This is needed to obtain the GUID and to set the volume.
> Expose IMMDevice

- CHANGELOG.md
- src/host/coreaudio/macos/mod.rs
On MacOS, `Device::supported_output/input_configs` returns multiple configs and they are the same values except for `min_samplerate` and `max_samplerate`. However, the pair of samplerates are always the same value like `min_samplerate:44100, max_samplerate:44100` and `min_samplerate:48000, max_samplerate:48000`. 
With this PR, `Device::supported_output/input_configs` now returns a combined `SupportedStreamConfig`. I found this problem when I tried to reorder the available streamconfigs depending on the parameter in my application.
On MacOS, `Device::default_input/output_config` does not use `cmp_default_heuristics` (I guess wasapi&asio are the same), but I hope this could be used in every platform ideally (though this PR does not address the implementation of the default config-related …
> [macOS] Fixed `SupportedStreamConfigRange` returns same `min_samplerate` and `max_samplerate`

- CHANGELOG.md
- src/host/alsa/enumerate.rs
- src/host/alsa/mod.rs
On one of my systems, cpal v0.16 enumerates these and only these devices:
```
1. "default"
2. "Yggdrasil+"
```
As reported in #991 this is problematic because it:
- misses a lot of virtual devices
- is unclear whether it's `hw`, `plughw`, something else
- only provides access to `DEV=0` when there could be more
- differs from ALSA idioms
This PR changes this behavior to enumerate all devices like `aplay -L` puts out:
```
1. "null"
2. "default"
3. "sysdefault"
4. "_audioout"
5. "_audioout__"
6. "alsaequal"
7. "plug_alsaequal"
8. "btstream"
9. "camilladsp"
10. "crossfeed"
11. "plug_bs2b"
12. "eqfa12p"
13. "plug_eqfa12p"
14. "invpolarity"
15. "trx_send"
16. "hw:CARD=Yggdrasil,DEV=0"
17. "plughw:CARD=Yggdrasil,DEV=0"
18. "default:CARD=Yggdrasil"
19. "sysdefault:CARD=Yggdrasil"
20. …
```
> fix: enumerate ALSA devices like aplay -L

- CHANGELOG.md
- src/samples_formats.rs
We already had `Sample::sample_size()` which returns the size in bytes of a format. This does not always correspond with the number of bits. For example, `I24` is stored in 4 bytes but with 24 bits storing audio, not 32. This PR introduces a new function `Sample::bits_per_sample()` to do that.
For `F32` or `F64` we could argue what it should return. This method returns 32/64 bits of _bit depth (storage)_ instead of 24/58 bits of _precision (effective resolution)_.
> feat: add Sample::bits_per_sample()

- CHANGELOG.md
- examples/synth_tones.rs
- src/host/alsa/mod.rs
- src/host/coreaudio/macos/mod.rs
- src/host/coreaudio/mod.rs
- src/host/wasapi/device.rs
- src/lib.rs
- src/samples_formats.rs
Adds support for 24-bit audio sample formats (`I24` and `U24`) stored in 4-byte containers across multiple backends. Thanks to @abique that originally proposed this with #918, which this supersedes.
Please help me test on Windows systems as I don't have access to a Windows development environment. The WASAPI implementation has been designed based on Windows audio API documentation but needs hardware validation.
Supersedes:
- #918
- #531
> feat: 24-bit sample format support (I24/U24)

- CHANGELOG.md
- src/host/alsa/mod.rs
- src/host/jack/stream.rs
- src/lib.rs
Improves audio callback performance through device-aware buffering, pre-allocation and period-aligned writes. This results in more consistent latency control and improved hot path performance.
Also fixes a DC offset issue with unsigned formats by proper silence (equilibrium) handling.
Queries device capabilities to determine which approach to use:
1. **Double buffering**: Uses 2 periods when user buffer fits within device limits
2. **Multi-period**: Calculates optimal period distribution for larger buffers
3. **Fallback**: Uses buffer-size-only for maximum device compatibility
- **Proper silence handling**: Fills buffers with correct equilibrium values for unsigned sample formats instead of zeros (prevents DC offset and pops)
- **Full period writes**: Always writes complete periods to …
> refactor(alsa): optimize period configuration and audio callback performance

- .github/workflows/cpal.yml
- CHANGELOG.md
- Cargo.toml
- src/host/wasapi/device.rs
- src/host/wasapi/stream.rs
Tests `windows` crate versions of the past 12 months for compatibility.
Supersedes #893
> ci: test compatibility with multiple windows crate versions
