alsa-sys/Cargo.toml

Testing the auto-publish thing.

Bump alsa-sys version

---

examples/music.rs
src/alsa/mod.rs
src/wasapi/mod.rs

Fix signed/unsigned formats mismatch

---

src/coreaudio/mod.rs
src/lib.rs

Fixes build. The crate on crates.io currently does not compile due to this.

Remove box feature usage

---

Cargo.toml
src/coreaudio/enumerate.rs
src/coreaudio/mod.rs
src/samples_formats.rs

Coreaudio compilation fixes

---

src/alsa/mod.rs

Fix underflow bug on linux

---

Cargo.toml

added arm target.  tested on bananapi w arch linux.

add ARM target

---

Cargo.toml
src/alsa/mod.rs

Fixes some possible compilation errors

Be more relaxed with c_void

---

Cargo.toml
src/coreaudio/mod.rs

From what I could gather from coreaudio-rs docs with my limited Rust knowledge this seems okay but please do review...

coreaudio: update to coreaudio-rs 0.5.0

---

src/coreaudio/mod.rs

As usual I don't have any OSX machine. It would be nice if someone could test it?
cc @mitchmindtree maybe?

Try fix the OSX code with futures

---

src/coreaudio/mod.rs

Since `play`/`pause` do not specify a Result return type, these will panic if the underlying calls to audiounit return `Err`.

[osx] Implement play/pause for coreaudio

---

alsa-sys/Cargo.toml

Bump alsa-sys version number

---

Cargo.toml

For publishing the fix in #154.

Publish 0.4.5 with recent macOS fix

---

src/coreaudio/mod.rs

Minor tweak for implicit error conversion to allow for direct `?` operator use in the coreaudio backend.

[coreaudio] Simplify error conversion

---

README.md

0.5 should be updated to 0.6 but I don't think it is necessary to keep this.

remove old doc

---

CHANGELOG.md
Cargo.toml

Will merge after #199 
cc @mitchmindtree

Publish 0.7

---

Cargo.toml

I'm trying to reduce duplicate dependencies in Amethyst, releasing this would help me in this endeavor.

Upgrade lazy_static

---

README.md

readme: mention system dependencies

---

src/alsa/mod.rs

This PR is based off of #235 in the hopes that it will be merged sometime soon. This PR returns errors from set_hw_params_from_format instead of panicking: This prevents a crash on linux when a user is running jack and selects it as the audio source.

Don't panic when setting hardware params in alsa

---

src/alsa/mod.rs
src/wasapi/stream.rs

ALSA and WASAPI backends now doesn't use a Mutex that is locked every time data is processed. These two backends were straightforward to modify, other backends were not modified.
Changes are self descriptive.

Use channels instead of mutex

---

src/host/coreaudio/mod.rs

This solution was originally posted by @HybridEidolon in #185. Sorry it
took so long! I thought it might be easier to open a new PR as half of
your implementation here has already been implemented in a following PR
(namely, the change from an unnecessary `Vec` of callbacks to a single
user callback).
Closes #185.
If someone on macOS could double check this is working that would be
appreciated! Otherwise I'll merge soon anyway as the change should be
pretty simple/straightforward.

Remove macOS sleep loop in favour of using `Condvar`

---

examples/enumerate.rs
src/platform/mod.rs

Add name to HostId

---

src/host/wasapi/stream.rs

The buffer size handling differs from what render streams uses. Logic is based on https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/WindowsAudioSession/cpp/WASAPICapture.cpp.
Fix #299

Fix WASAPI capture logic

---

.travis.yml

Faster is better, let's enable it.

Travis: enable Cargo cache

---

README.md

Updates the README.md badge to use the RustAudio user.

Fix README.md builds badge

---

.github/workflows/cpal.yml
src/host/alsa/mod.rs

This PR fixes the `clippy-action` error
Thanks in advance for your review! :)

Fix the clippy-action

---

.github/workflows/cpal.yml

It re-enables the `clippy-check `action for PRs. I would like to thank @svartalf for the support!
Thanks in advance for your review! :)

Enable clippy-check for pull requests

---

.github/workflows/cpal.yml

Since `Windows` now uses `Powershell` as default shell
Thanks in advance for your review! :)

Update Github Actions for Windows

---

.github/workflows/cpal.yml

- Speed up toolchain installation
- Try to fix `cargo publish`

Update and fix Github Actions

---

.github/workflows/cpal.yml

Allow `cargo-publish` to fail for now.
Looking for better solutions...

Allow cargo-publish failure

---

src/host/coreaudio/enumerate.rs
src/host/coreaudio/mod.rs

Hi,
I cloned the repo and noticed some warnings for simple things and figured I'd squash them real quick.

Fixed compiler warnings

---

Cargo.toml
src/host/alsa/mod.rs
src/host/mod.rs
src/platform/mod.rs

DragonFly has the same audio system as FreeBSD.

DragonFly support

---

src/host/wasapi/device.rs
src/host/wasapi/stream.rs

This uses `ptr::null_mut()` and `MaybeUninit` to remove use of
deprecated `mem::uninitialized()` which could possibly result in UB.

Address deprecated `mem::uninitialized` warnings in WASAPI host

---

src/host/coreaudio/mod.rs

Fixes https://github.com/RustAudio/cpal/issues/398

macOS: fallback to CFStringGetCString if CFStringGetCStringPtr returns nil

---

CHANGELOG.md
Cargo.toml

Publish version 0.12.0

---

asio-sys/Cargo.toml

Asio-sys dependency updates

---

CHANGELOG.md
Cargo.toml

Followup of #455 to fix #450 .

Release 0.12.1

---

.github/workflows/cpal.yml
src/platform/mod.rs

Also remove other references to EventLoop

Fix compilation error when using null host

---

src/lib.rs

SampleRate: Implement std::ops::{Div, Mul}

---

.github/workflows/cpal.yml
CHANGELOG.md
Cargo.toml
examples/beep.rs
src/host/oboe/convert.rs
src/host/oboe/input_callback.rs
src/host/oboe/mod.rs
src/host/oboe/output_callback.rs

This PR adds APK build CI as was said in [this comment](https://github.com/RustAudio/cpal/pull/468#issuecomment-717177006).
Also, publish a new release to update Rodio.

Add Android APK build CI and Release version 0.13.0

---

.github/workflows/cpal.yml
Cargo.toml

Bumps Android dependencies to their latest versions :)

Bump Android dependencies

---

Cargo.toml

Bumps ndk dependencies to their latest versions :)

Bump ndk dependencies

---

CHANGELOG.md
Cargo.toml

The 0.13.4 release, so that the bugfix PR #597 gets out.

Release 0.13.4

---

Cargo.toml
src/host/alsa/mod.rs

Also fixes the build. Fixes #610

Update alsa and nix dependencies

---

Cargo.toml

Upgrade ndk and ndk-glue dependencies, both to 0.4.0

---

Cargo.toml

This fixes the build with Pipewire's implementation of JACK:
https://github.com/RustAudio/rust-jack/pull/154

update jack to 0.8

---

src/host/alsa/mod.rs

Fallback to monotonic timestamp if monotonic_raw can be set up

---

Cargo.toml

Mostly for fixing https://github.com/bevyengine/bevy/issues/3648

Bump ndk/ndk-glue to 0.7

---

CHANGELOG.md
Cargo.toml

Release 0.14.0

---

Cargo.toml
examples/beep.rs
examples/feedback.rs
examples/record_wav.rs
src/host/alsa/mod.rs
src/host/mod.rs
src/platform/mod.rs

Tested on NetBSD-current (development branch, 9.99.100)
Built with Rust-1.64.0
Tests work and output sound.

Add NetBSD support

---

Cargo.toml

Update oboe dependency

---

CHANGELOG.md
Cargo.toml

Release 0.15.0

---

asio-sys/src/bindings/mod.rs

Remove unnecessary Lazy Mutex.
Change to non-mut static.
https://github.com/RustAudio/cpal/pull/775#discussion_r1166606279

Remove unnecessary Lazy Mutex

---

examples/synth_tones.rs

Now also plays through a series of waveforms :)
Also here making some aesthetic judgements on naming/convention which am very happy to have a conversation about!

Improve synth tones example

---

Cargo.toml

update ndk to the latest version, 0.8
tested with Bevy and https://github.com/katyo/oboe-rs/pull/57

update ndk to 0.8

---

.github/workflows/cpal.yml

download the android platform used by default by cargo apk

fix CI on android

---

asio-sys/Cargo.toml
asio-sys/build.rs
asio-sys/src/bindings/asio_import.rs
asio-sys/src/bindings/errors.rs
asio-sys/src/bindings/mod.rs
asio-sys/src/lib.rs

- Fixed clippy warnings
- Removed once_cell
- Added call to ASIOOutputReady (see ASIO docs)

Cleaned up asio-sys

---

src/host/wasapi/device.rs

This will detect some new supported sample formats (for example U8, I16 and I32) for WASAPI devices

Improved detection of WASAPI device formats

---

Cargo.toml
src/host/asio/device.rs
src/host/asio/stream.rs

- Fixed ASIO output stream mixing
- Fixed some clippy warnings
- Fixed silencing of buffer when multiple ASIO device streams

ASIO audio mixing fixes

---

Cargo.toml

Oboe was update to 0.6 https://github.com/katyo/oboe-rs/releases/tag/0.6.0

update oboe to 0.6

---

Cargo.toml
src/host/wasapi/com.rs
src/host/wasapi/device.rs
src/host/wasapi/stream.rs

windows 0.52 -> 0.54

---

src/samples_formats.rs

Fix some inconsistencies and enhance the documentation of `SampleFormat`.

doc: improvements for SampleFormat

---

examples/ios-feedback/README.md

fix typo (still -> install)

---

src/host/coreaudio/macos/mod.rs

Checked out the code locally and noticed an unused import.

Remove unused import

---

CHANGELOG.md

As mentioned in https://github.com/RustAudio/cpal/pull/978#issuecomment-2952782267

Fix release date for v0.16

---

CHANGELOG.md
examples/wasm-beep/Cargo.toml
examples/wasm-beep/src/lib.rs

See: https://github.com/RustAudio/cpal/security/dependabot/49

security: remove wee_alloc dependency and related code
